export const GET_STAR_MOVIE = "GET_STAR_MOVIE";
export const GET_POPULAR_MOVIES = "GET_POPULAR_MOVIES";
export const GET_MODAL_STATE = "GET_MODAL_STATE";
export const GET_DROPDOWN_VALUE = "GET_DROPDOWN_VALUE";
